export const TAG_LIST: any = {
  CULTURAL: {
    id: 1,
    title: '문화활동',
    list: [
      { id: 1, name: '전시' },
      { id: 2, name: '영화' },
      { id: 3, name: '뮤지컬' },
      { id: 4, name: '공연' },
      { id: 5, name: '연극' },
      { id: 6, name: '콘서트' },
      { id: 7, name: '지역축제' },
    ],
  },
  EXERCISE: {
    id: 2,
    title: '운동/액티비티',
    list: [
      { id: 8, name: '러닝' },
      { id: 9, name: '등산' },
      { id: 10, name: '산책' },
      { id: 11, name: '헬스' },
      { id: 12, name: '필라테스' },
      { id: 13, name: '요가' },
      { id: 14, name: '홈트' },
      { id: 15, name: '자전거' },
      { id: 16, name: '서핑' },
      { id: 17, name: '배드민턴' },
      { id: 18, name: '축구' },
      { id: 19, name: '농구' },
      { id: 20, name: '탁구' },
      { id: 21, name: '볼링' },
      { id: 22, name: '골프' },
      { id: 23, name: '당구' },
    ],
  },
  FOOD: {
    id: 3,
    title: '음식',
    list: [
      { id: 24, name: '카페' },
      { id: 25, name: '맛집' },
      { id: 26, name: '음주' },
      { id: 27, name: '요리' },
    ],
  },
  CREATIVE: {
    id: 4,
    title: '취미/창작',
    list: [
      { id: 28, name: '독서' },
      { id: 29, name: '드로잉' },
      { id: 30, name: '사진' },
      { id: 31, name: '방탈출' },
      { id: 32, name: '댄스' },
      { id: 33, name: '악기' },
      { id: 34, name: '영상' },
      { id: 35, name: '반려 동물' },
      { id: 36, name: '글쓰기' },
    ],
  },
  TRAVEL: {
    id: 5,
    title: '여행',
    list: [
      { id: 37, name: '피크닉' },
      { id: 38, name: '드라이브' },
      { id: 39, name: '캠핑' },
      { id: 40, name: '국내여행' },
      { id: 41, name: '해외여행' },
    ],
  },
};
